#!/usr/bin/env bash
yay_ft() {
    yay -S --noconfirm --needed "$1"
}

pacman_ft(){
    sudo pacman -S --needed --noconfirm "$1"
}

# Setup yay
pacman_ft base-devel
git clone https://aur.archlinux.org/yay.git
pushd yay || exit
makepkg -si --needed --noconfirm
yay -Sua --noconfirm --needed
popd || exit

# Update the Operating System
sudo pacman -Syuu

