#!/usr/bin/env bash
paru_ft() {
    paru -S --noconfirm --needed "$1"
}

pacman_ft(){
    sudo pacman -S --needed --noconfirm "$1"
}

# Setup Paru
pacman_ft base-devel
git clone https://aur.archlinux.org/paru.git
pushd paru || exit
makepkg -si --needed --noconfirm
paru -Sua --noconfirm --needed
popd || exit

# Update the Operating System
sudo pacman -Syuu

