#!/usr/bin/env bash
sudo apt install -y ansible snap

sudo snap install snapd

LATEST_VERSION=$(curl --silent https://api.github.com/repos/tofuutils/tenv/releases/latest | jq -r .tag_name)
curl -O -L "https://github.com/tofuutils/tenv/releases/latest/download/tenv_${LATEST_VERSION}_amd64.deb"
sudo dpkg -i "tenv_${LATEST_VERSION}_amd64.deb"

if [ -n "$ZSH_VERSION" ]; then
    exec zsh -l
elif [ -n "$BASH_VERSION" ]; then
    exec bash -l
fi
tenv tofu install latest
tenv tf install latest

# ## This component sets up the terraform linter and teraform lauguage server
curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | sudo bash
sudo apt install -y terraform-ls 

# Install Packer via Deb
curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(grep -oP '(?<=UBUNTU_CODENAME=).*' /etc/os-release || lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
sudo apt-get update && sudo apt-get install packer

# Setup the Virt Cusomize Component
sudo apt install libguestfs-tools -y

# Setup of the Qemu Server Services on the machine
sudo apt install qemu-system-x86 qemu-system cpu-checker -y
