#!/usr/bin/env bash
sudo apt -y install git ripgrep jq tldr shutter fzf bc

# Setup tldr
mkdir -p $HOME/.local/share/tldr
sudo apt install tldr -y
tldr --update --color --auto-update-interval 5

# Install TheFuc
sudo apt install snapd -y
sudo snap install snapd
sudo snap install --classic --beta thefuck
