#!/usr/bin/env bash
sudo apt -y install git ripgrep jq tldr shutter python3-pip python3

# Setup tldr
mkdir -p $HOME/.local/share/tldr
sudo apt install tldr -y
tldr --update --color --auto-update-interval 5

# Install TheFuck
sudo snap install snapd
sudo snap install --classic --beta thefuck