#!/usr/bin/env bash

# Install Zsh
sudo apt install zsh -y
hash -r

# Change the default shell to zsh
zshstatus=$(echo $SHELL | grep zsh)
if [ -z "$zshstatus" ]; then
  echo "Changing default shell to zsh for user $USER"
  dirzsh=$(which zsh)
  sudo chsh -s "$dirzsh" "$USER"
  declare -x SHELL=$(which zsh)

  # Install Oh My Zsh
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
fi
# Define the ZSH_CUSTOM variable if it is not already set
if [ -z "$ZSH_CUSTOM" ]; then
  export ZSH_CUSTOM=~/.oh-my-zsh/custom
fi

# Clone the zsh-autosuggestions plugin
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting

# Clone the zsh-autosuggestions plugin
git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
