#!/usr/bin/env bash
paru_ft() {
    sudo paru -S --noconfirm --needed "$1"
}

pacman_ft(){
    sudo pacman -S --needed --noconfirm "$1"
}

# Install the baseline of tools required
pacman_ft git make
paru_ft go go-tools  


# Install Teraform Installer and Teraform Lauguage Server
paru_ft tenv-bin terraform-ls
# This is installing teraform and OpenTofu for me
# https://github.com/tofuutils/tenv
tenv tofu install
tenv tf install

# Install Packer
paru_ft packer

# Setup of the Qemu Server Services on the machine
pacman_ft qemu-system-x86 qemu-system cpu-checker libguestfs-tools
