#!/usr/bin/env bash
paru_ft() {
    paru -S --noconfirm --needed "$1"
}

pacman_ft(){
    sudo pacman -S --needed --noconfirm "$1"
}
# Install the docker components onto the system
paru_ft docker docker-buildx docker-compose containerd
# Create the docker group and add the current user to it:
sudo groupadd docker
sudo usermod -aG docker $USER
