#!/usr/bin/env bash
paru_ft() {
    paru-S --noconfirm --needed "$1"
}

pacman_ft(){
    sudo pacman -S --needed --noconfirm "$1"
}

# Setup the base tools on the enviroment
pacman_ft install git ripgrep jq tldr shutter fzf bc

# Setup tldr
mkdir -p $HOME/.local/share/tldr
pacman_ft tldr
tldr --update --color --auto-update-interval 5

# Install TheFuc
paru_ft thefuck
