#!/usr/bin/env bash
paru_ft() {
    sudo paru -S --noconfirm --needed "$1"
}

pamac_ft(){
    sudo pamac -S --needed --noconfirm "$1"
}

pamac_ft neovim lua51 luarocks lua-language-server
paru_ft nerd-fonts-git

