#!/usr/bin/env bash
paru_ft() {
    paru-S --noconfirm --needed "$1"
}

pacman_ft(){
    sudo pacman -S --needed --noconfirm "$1"
}

pacman_ft neovim lua51 luarocks lua-language-server
paru_ft nerd-fonts-git

