#!/usr/bin/env bash
paru_ft() {
    sudo paru -S --noconfirm --needed "$1"
}

pacman_ft(){
    sudo pacman -S --needed --noconfirm "$1"
}

pacman_ft wireguard wireguard-tools nmap
pacman_ft lftp
pacman_ft btop htop
pacman_ft nfs-common rsync

# pacman_ft zram-generator zstd gambas3-gb-compress python-pyzstd \
#  python-zstandard zarchive lib32-zstd lz4 python-lz4 lib32-lz4