#!/usr/bin/env bash
yay_ft() {
    yay -S --noconfirm --needed "$1"
}

pacman_ft(){
    sudo pacman -S --needed --noconfirm "$1"
}

# Install Zsh
pacman_ft zsh bat -y
hash -r

# Change the default shell to zsh
zshstatus=$(echo $SHELL | grep) 
if [ -z "$zshstatus" ]; then
  echo "Changing default shell to zsh for user $USER"
  dirzsh=$(which zsh)
  sudo chsh -s "$dirzsh" "$USER"
  declare -x SHELL=$(which zsh)

fi
  # Install Oh My Zsh
  sudo rm -rf ~/.config/oh-my-zsh
  sudo chmod 777 ~/.config
  ZSH=~/.config/oh-my-zsh sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh) --unattended"

  
  if [ -d ~/.config ]; then
    echo config directory exists
  else
    sudo mkdir ~/.config
  fi 
  export ZSH_CUSTOM=~/.config/oh-my-zsh/custom

# Clone the zsh-autosuggestions plugin
sudo rm -rf "${ZSH_CUSTOM:-~/.oh-my-zsh/custom}"/plugins/zsh-syntax-highlighting
sudo git clone https://github.com/zsh-users/zsh-syntax-highlighting.git "${ZSH_CUSTOM:-~/.oh-my-zsh/custom}"/plugins/zsh-syntax-highlighting

# Clone the zsh-autosuggestions plugin
sudo rm -rf "${ZSH_CUSTOM:-~/.oh-my-zsh/custom}"/plugins/zsh-autosuggestions
sudo git clone https://github.com/zsh-users/zsh-autosuggestions "${ZSH_CUSTOM:-~/.oh-my-zsh/custom}"/plugins/zsh-autosuggestions

# clone the z directory healper
# This plugin provides a way to quickly navigate to frequently used directories.
sudo rm -rf "${ZSH_CUSTOM:-~/.oh-my-zsh/custom}"/plugins/zsh-z
sudo git clone https://github.com/agkozak/zsh-z "${ZSH_CUSTOM:-~/.oh-my-zsh/custom}"/plugins/zsh-z

# setup zsh-bat plugin
# This plugin provides syntax highlighting for the `bat` command in zsh.
sudo rm -rf "$ZSH_CUSTOM"/plugins/zsh-bat
sudo git clone https://github.com/fdellwing/zsh-bat.git "${ZSH_CUSTOM:-~/.oh-my-zsh/custom}"/plugins/zsh-bat

