#!/usr/bin/env bash
paru_ft() {
    sudo paru -S --noconfirm --needed "$1"
}

pacman_ft(){
    sudo pacman -S --needed --noconfirm "$1"
}

# Install Zsh
pacman_ft zsh bat -y
hash -r

# Change the default shell to zsh
zshstatus=$(echo $SHELL | grep zsh)
if [ -z "$zshstatus" ]; then
  echo "Changing default shell to zsh for user $USER"
  dirzsh=$(which zsh)
  sudo chsh -s "$dirzsh" "$USER"
  declare -x SHELL=$(which zsh)

  # Install Oh My Zsh
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  
  if [ -d ~/.config ]; then
    echo config directory exists
  else
    sudo mkdir ~/.config
  fi 
  mv -f ~/.oh-my-zsh ~/.config/oh-my-zsh
  rm -rf ~/.oh-my-zsh
fi

# Define the ZSH_CUSTOM variable if it is not already set
if [ -z "$ZSH_CUSTOM" ]; then
  export ZSH_CUSTOM=~~/.config/oh-my-zsh/custom
fi

# Clone the zsh-autosuggestions plugin
sudo rm -rf "${ZSH_CUSTOM:-~/.oh-my-zsh/custom}"/plugins/zsh-syntax-highlighting
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git "${ZSH_CUSTOM:-~/.oh-my-zsh/custom}"/plugins/zsh-syntax-highlighting

# Clone the zsh-autosuggestions plugin
sudo rm -rf "${ZSH_CUSTOM:-~/.oh-my-zsh/custom}"/plugins/zsh-autosuggestions
git clone https://github.com/zsh-users/zsh-autosuggestions "${ZSH_CUSTOM:-~/.oh-my-zsh/custom}"/plugins/zsh-autosuggestions

# clone the z directory healper
# This plugin provides a way to quickly navigate to frequently used directories.
sudo rm -rf "${ZSH_CUSTOM:-~/.oh-my-zsh/custom}"/plugins/zsh-z
git clone https://github.com/agkozak/zsh-z "${ZSH_CUSTOM:-~/.oh-my-zsh/custom}"/plugins/zsh-z

# setup zsh-bat plugin
# This plugin provides syntax highlighting for the `bat` command in zsh.
sudo rm -rf "$ZSH_CUSTOM"/plugins/zsh-bat
git clone https://github.com/fdellwing/zsh-bat.git "${ZSH_CUSTOM:-~/.oh-my-zsh/custom}"/plugins/zsh-bat

