#!/usr/bin/env bash
yay_ft() {
    yay -S --noconfirm --needed "$1"
}

pacman_ft(){
    sudo pacman -S --needed --noconfirm "$1"
}

# Microsoft Visual Studio Code
pacman_ft code github-cli
# Github Desktop
yay_ft github-desktop-git
