#!/usr/bin/env bash
yay_ft() {
    yay -S --noconfirm --needed "$1"
}

pacman_ft(){
    sudo pacman -S --needed --noconfirm "$1"
}

# This is Telegram Desktop
#yay_ft ayugram-desktop

pacman_ft telegram-desktop
