#!/usr/bin/env bash
yay_ft() {
    yay -S --noconfirm --needed "$1"
}

pacman_ft(){
    sudo pacman -S --needed --noconfirm "$1"
}

pacman_ft neovim lua51 luarocks lua-language-server
# yay_ft nerd-fonts-git

