#!/usr/bin/env bash
yay_ft() {
    yay -S --noconfirm --needed "$1"
}

pacman_ft(){
    sudo pacman -S --needed --noconfirm "$1"
}

pacman_ft wireguard wireguard-tools nmap
pacman_ft lftp
pacman_ft btop htop
pacman_ft nfs-utils  rsync